// AYVAZ Master Alignment — embedded directly in code.
// GENERATED by scripts/generate-alignment.js — do not edit by hand.
// Source: AYVAZ Master Alignment P10 REV 092926.xlsx
// Last updated: P10 REV 092926

const MASTER_ALIGNMENT_TEXT = `
AYVAZ PIZZA LLC — MASTER STORE ALIGNMENT (P10 REV 092926)

VP of Operations: Matt Hester

  Region Coach: Harold Lacoste

    AC: Darian Spikes | Area 2011 | dspikes@ayvazpizza.com
      038876 | Senoia, GA | RGM: Michelle Philipp
      039377 | Griffin, GA | RGM: Patricia Washington
      039378 | Union City, GA | RGM: Kirk Browne
      039379 | Newnan, GA | RGM: Jasmine Mozley
      039384 | Newnan, GA | RGM: Michael Hayes
      039454 | Griffin, GA | RGM: Candice Weston
      039465 | Fairburn, GA | RGM: Shawntae Hubbard

    AC: Ebony Simmons | Area 2016 | esimmons@ayvazpizza.com
      039383 | Stockbridge, GA | RGM: Ronald George
      039388 | McDonough, GA | RGM: Sylvia Brown
      039393 | Hampton, GA | RGM: Judah Howard
      039429 | McDonough, GA | RGM: Hildeza Roxborough
      039461 | Fayetteville, GA | RGM: Cynthia Vining
      039513 | Stockbridge, GA | RGM: Michael Abernathy
      039521 | McDonogh, GA | RGM: Veronica McWilliams
      039522 | Ellenwood, GA | RGM: Gary Burney

    AC: Jadon McNeil | Area 2022 | jmcneil@ayvazpizza.com
      039375 | Kennesaw, GA | RGM: Krystle Presnell
      039376 | Dallas, GA | RGM: OPEN
      039382 | Acworth, GA | RGM: Rocquel Anderson
      039387 | Kennesaw, GA | RGM: Alana Pate
      039392 | Woodstock, GA | RGM: Matthew Gaddy

    AC: Jorge Garcia | Area 2000 | jgarcia@ayvazpizza.com
      039380 | Marietta, GA | RGM: Naaja Bloodsoe
      039386 | Powder Springs, GA | RGM: Dasha Lane
      039389 | Lithia Springs, GA | RGM: Karla Moore
      039410 | Mableton, GA | RGM: Rupesh Patel
      039451 | Atlanta, GA | RGM: Keane Leslie

    AC: Marc Gannon | Area 2015 | mgannon@ayvazpizza.com
      039412 | Fort Walton Beach, FL | RGM: Dawn Lee
      039413 | Navarre, FL | RGM: James Carnes
      039415 | Miramar Beach, FL | RGM: James Haberlin
      039416 | Niceville, FL | RGM: Robert Lowe
      039430 | Fort Walton Beach, FL | RGM: Brandon Seeley
      039529 | Crestview, FL | RGM: Rebecca Anderson
      042659 | Destin, FL | RGM: Andrae Taylor

    AC: Michelle Meehan | Area 2034 | mmeehan@ayvazpizza.com
      039381 | Douglasville, GA | RGM: OPEN
      039385 | Douglasville, GA | RGM: Austin Zavala
      039391 | Douglasville, GA | RGM: Stephen Payton
      039526 | Dallas, GA | RGM: Isaac Bowens

  Region Coach: Lori Schwartz

    AC: Debbra Selvig | Area 2013 | dselvig@ayvazpizza.com
      039341 | Hastings, MN | RGM: OPEN
      039344 | Spring Lake Park, MN | RGM: James Johnson
      039352 | Maplewood, MN | RGM: Jesse Cortes
      039354 | Cottage Grove, MN | RGM: Lisa Kratzke
      039364 | Inver Grove Heights, MN | RGM: Devin Boyer
      039460 | Woodbury, MN | RGM: Sarah Hansen
      041084 | St Paul, MN | RGM: Cherry Bailey

    AC: Derek King | Area 2057 | dking@ayvazpizza.com
      039336 | Cloquet, MN | RGM: Jamie Mueller
      039337 | Virginia, MN | RGM: Jeremy Rice
      039339 | Baxter, MN | RGM: Joshua Rinde
      039340 | Bemidji, MN | RGM: Mackenzie Raisch
      039441 | Duluth, MN | RGM: Annabelle Schleret
      039467 | Duluth, MN | RGM: OPEN

    AC: Scott Fiksdal | Area 2049 | sfiksdal@ayvazpizza.com
      039338 | Mason City, IA | RGM: Kristine Hempfner
      039342 | Rochester, MN | RGM: Joseph Houston
      039356 | Mankato, MN | RGM: Paul Wood
      039357 | Rochester, MN | RGM: Allen Hollins
      039366 | Farmington, MN | RGM: OPEN
      039371 | Fairbault, MN | RGM: Carrie Jenkins
      039437 | Austin, MN | RGM: Shawn Olson
      039464 | Lakeville, MN | RGM: Denise Garcia

    AC: Szymon Lubas | Area 2044 | slubas@ayvazpizza.com
      039343 | Shakopee, MN | RGM: Jonathan Peterson
      039348 | Bloomington, MN | RGM: Daniel Champagne
      039353 | Burnsville, MN | RGM: Elisa Cantu
      039358 | Apple Valley, MN | RGM: Denzel Knapp
      039360 | Bloomington, MN | RGM: Charlie Garrett
      039363 | Eagan, MN | RGM: Leah Jeurissen
      039368 | Prior Lake, MN | RGM: Daniel Sutcliffe-Isham
      039440 | Minneapolis, MN | RGM: Andrew Karis
      039449 | Columbia Heights, MN | RGM: Sheri Matusovic

    AC: Va Vang | Area 2012 | vvang@ayvazpizza.com
      039346 | Brooklyn Center, MN | RGM: Kong Pang Vang
      039347 | Minneapolis, MN | RGM: Jonathan Burgos-Hernandez
      039355 | Minneapolis, MN | RGM: Kerry Roberts
      039367 | Champlin, MN | RGM: Alicia Dabrowski
      039370 | Delano, MN | RGM: James Kinneman
      039439 | St Cloud, MN | RGM: Gabrielle Iehl
      039459 | Maple Grove, MN | RGM: OPEN

  Region Coach: Preston Arnwine

    AC: Emmanuel Boateng | Area 2017 | eboateng@ayvazpizza.com
      039418 | Danville, VA | RGM: Erica Scales
      039422 | Burlington, NC | RGM: Lashanti Gregg
      039423 | Graham, NC | RGM: Anna Quiah
      039432 | Mebane, NC | RGM: Barry Candy
      039433 | Greensboro, NC | RGM: Anna Taylor
      039455 | Greensboro, NC | RGM: Jessica Lowe
      039456 | Whitsett, NC | RGM: Angie Bouchard

    AC: Erin Pizzo | Area 2004 | epizzo@ayvazpizza.com
      039420 | Harrisonburg, VA | RGM: Cristal Humes
      039425 | Elkton, VA | RGM: Sabrina Hensley
      039426 | Woodstock, VA | RGM: Kristan Sieben
      039431 | Staunton, VA | RGM: Zachary Gray
      039435 | Charlottesville, VA | RGM: Debra White
      039450 | Orange, VA | RGM: Stacey Moffitt
      039453 | Harrisonburg, VA | RGM: Chris Kanode
      039466 | Waynesboro, VA | RGM: Daniel Lamb

    AC: Jason McNeal | Area 2009 | jmcneal@ayvazpizza.com
      039397 | Florence, SC | RGM: Larone Wilson
      039400 | Florence, SC | RGM: Regena Peguese
      039401 | Darlington, SC | RGM: Tysheika Moore
      039402 | Florence, SC | RGM: Marquisha Grice
      039403 | Marion, SC | RGM: Meghan Lovelace
      039409 | Hartsville, SC | RGM: Ebony Bristow

    AC: Russell Kowalczyk | Area 2048 | rkowalczyk@ayvazpizza.com
      039394 | Elberton, GA | RGM: Kristy Allen
      039395 | Abbeville, SC | RGM: Zea Bond
      039396 | Hartwell, GA | RGM: Shannon Daye
      039398 | Royston, GA | RGM: Louella Ledsome
      039399 | Lavonia, GA | RGM: Jeremy Downing
      039404 | Greenwood, SC | RGM: Billy Stone
      039405 | Simpsonville, SC | RGM: Angela Thornton
      039407 | Newberry, SC | RGM: Jackalon Spatafora
      039408 | Seneca, SC | RGM: OPEN

    AC: Stepfen White | Area 2041 | swhite@ayvazpizza.com
      039419 | Martinsville, VA | RGM: April Wright
      039424 | Greensboro, NC | RGM: Megan Cain
      039427 | Greensboro, NC | RGM: Sherla Jensen
      039436 | Greensboro, NC | RGM: Tammy Holt
      039457 | Greensboro, NC | RGM: Angela Wilson

VP of Operations: Tracy Krumwiede

  Region Coach: Jerry Warren

    AC: Alpha Garza | Area 2042 | agarza@ayvazpizza.com
      039289 | Houston, TX | RGM: Charles Walker
      039320 | Houston, TX | RGM: Seanelle Oliver
      039321 | Houston, TX | RGM: Ashley Solis
      039326 | Houston, TX | RGM: Maria Nunez
      039329 | Houston, TX | RGM: Courtland Jamon
      039438 | Houston, TX | RGM: Evette Rodriguez
      039524 | Houston, TX | RGM: Virginia Basey

    AC: Amanda Spikes | Area 2001 | aspikes@ayvazpizza.com
      039248 | Spring, TX | RGM: Dolores Bishop
      039249 | The Woodlands, TX | RGM: Jessica Ramirez
      039251 | Humble, TX | RGM: Shawta Godfrey
      039266 | Spring, TX | RGM: Brittany Horn
      039300 | Spring, TX | RGM: Tara Dugas
      039304 | Tomball, TX | RGM: Miguel Palacios
      039519 | Spring, TX | RGM: Korosh Memar
      039528 | The Woodlands, TX | RGM: Stevie Reid

    AC: Imran Awan (Kiosks-Express) | Area 2100 | imranaway@gulshaninc.com
      317872 | Houston, TX | RGM: TBD
      788190 | Houston, TX | RGM: Arshad Hussain
      788192 | Houston, TX | RGM: Fawad Mangi
      788195 | Pearland, TX | RGM: Javed Baloch
      788196 | Houston, TX | RGM: Dewayne Davis
      788197 | Houston, TX | RGM: Mehdi Karimi
      788378 | Richmond, TX | RGM: Syed Rizvi
      788379 | Booth, TX | RGM: Zaid Kapadia
      788380 | Katy, TX | RGM: Fouzia Chowdhury
      788381 | Houston, TX | RGM: Riaz Rehman
      788385 | The Woodlands, TX | RGM: TBD
      788411 | The Woodlands, TX | RGM: TBD
      788423 | Houston, TX | RGM: Rayonte Hamilton
      788424 | Houston, TX | RGM: Brandon Mentor
      788426 | Houston, TX | RGM: TBD
      788427 | Houston, TX | RGM: TBD

    AC: Larry (Steve) Battenfield | Area 2050 | sbattenfield@ayvazpizza.com
      039261 | Kingwood, TX | RGM: Stacey Hendrix
      039293 | Crosby, TX | RGM: Joshua Johnson
      039298 | Kingwood, TX | RGM: Marina Keller
      039303 | Porter, TX | RGM: Joshua Guidry
      039305 | Humble, TX | RGM: Timothy Stringfellow
      039308 | Liberty, TX | RGM: Holly Garcia
      039325 | New Caney, TX | RGM: Melissa Carrasco
      039331 | Dayton, TX | RGM: Ruth Nugent

    AC: Thomas Cobb | Area 2030 | tcobb@ayvazpizza.com
      039245 | Houston, TX | RGM: Venessa Rivera
      039250 | Spring, TX | RGM: Dalila Rendon
      039253 | Houston, TX | RGM: Celene Carmona
      039254 | Houston, TX | RGM: Manuel Lopez
      039272 | Houston, TX | RGM: Resanell Russell
      039281 | Cypress, TX | RGM: Zachary Broussard
      039291 | Houston, TX | RGM: Kirkland Johnson

  Region Coach: Jose Lozano Sr.

    AC: Joel Salinas | Area 2019 | jsalinas@ayvazpizza.com
      039474 | Brownsville, TX | RGM: Jacquelyn Rivas
      039479 | Brownsville, TX | RGM: Roberto Serna
      039487 | Brownsville, TX | RGM: Kerry Silva
      039488 | Brownsville, TX | RGM: Carlos Martinez
      039503 | South Padre Island, TX | RGM: Glafira Peña
      039505 | Port Isabel, TX | RGM: Emma Salas
      039523 | Brownsville, TX | RGM: Gabriela Torres

    AC: Jose Flores | Area 2027 | jflores@ayvazpizza.com
      039470 | Edinburg, TX | RGM: Amy Gutierrez
      039493 | Alamo, TX | RGM: Armand Hinojosa
      039494 | Mission, TX | RGM: Ramon Valdez
      039501 | San Juan, TX | RGM: Heidy Perez
      039506 | Mission, TX | RGM: Ismena Marroquin
      039507 | Mission, TX | RGM: Miguel Garcia
      039510 | Palmhurst, TX | RGM: Jose Lozano Jr.

    AC: Lee Duran | Area 2035 | lduran@ayvazpizza.com
      039468 | McAllen, TX | RGM: Melissa De La Garza
      039469 | McAllen, TX | RGM: OPEN
      039471 | McAllen, TX | RGM: Daniel Lopez
      039476 | McAllen, TX | RGM: Brenna Gagne
      039480 | Pharr, TX | RGM: Noemi Rodriguez
      039486 | McAllen, TX | RGM: Cynthia Palmer
      039516 | Pharr, TX | RGM: Guadalupe Cortez

    AC: Lonie Johnson Jr | Area 2021 | ljohnson@ayvazpizza.com
      039218 | Carrizo Springs, TX | RGM: Linda Longoria
      039219 | Crystal City, TX | RGM: Norma Hernandez
      039220 | Del Rio, TX | RGM: Ana Camara
      039221 | Eagle Pass, TX | RGM: Jose Martinez
      039236 | Uvalde, TX | RGM: Scott Schaefer
      039443 | Eagle Pass, TX | RGM: Carlos Castillo

    AC: Maria Avila | Area 2038 | mavila@ayvazpizza.com
      039227 | Rio Grande City, TX | RGM: Dora Rodriguez
      039228 | Roma, TX | RGM: Gilberto Flores
      039485 | Laredo, TX | RGM: Ricardo Gonzalez
      039492 | Laredo, TX | RGM: Ruth Gonzalez
      039496 | Laredo, TX | RGM: Ruby Gonzalez
      039504 | Zapata, TX | RGM: Jose Valadez
      040768 | Laredo, TX | RGM: Yessenia Juarez

    AC: Michelle Cavazos | Area 2040 | mcavazos@ayvazpizza.com
      039335 | Cotulla, TX | RGM: Alejandro Villegas
      039473 | Laredo, TX | RGM: Michelle De La Cruz
      039478 | Laredo, TX | RGM: Jorge Meza
      039491 | Laredo, TX | RGM: Ricardo Esparza
      039499 | Laredo, TX | RGM: Ramiro Garcia
      039502 | Laredo, TX | RGM: Marie Gonzalez
      039512 | Laredo, TX | RGM: Anthony Tejeda

    AC: Roberto Sanchez | Area 2029 | rsanchez@ayvazpizza.com
      039472 | Harlingen, TX | RGM: Eddie Ortiz
      039481 | Raymondville, TX | RGM: Jasmin Herrera
      039482 | Mercedes, TX | RGM: Jesus Gonzalez
      039484 | Harlingen, TX | RGM: Hernan Osequera
      039490 | Harlingen, TX | RGM: Randall Rosales
      039498 | San Benito, TX | RGM: Ashley Gutierrez
      040916 | La Feria, TX | RGM: Luis Lozano
      041948 | Los Fresnos, TX | RGM: Yvette Rios

    AC: Ruben Gonzalez | Area 2047 | rgonzalez@ayvazpizza.com
      039475 | Weslaco, TX | RGM: Linda Rangel
      039483 | Edinburg, TX | RGM: Felix Jaramillo
      039489 | Donna, TX | RGM: Osbaldo Luna
      039495 | Elsa, TX | RGM: Alejandro Escobedo
      039497 | Weslaco, TX | RGM: Veronica Lopez
      039508 | Edinburg, TX | RGM: Nereyda Moreno
      039509 | Edinburg, TX | RGM: Maria Solis
      039517 | Edinburg, TX | RGM: Angel Mejia

  Region Coach: Papa Diack

    AC: Jeffrey Washburn | Area 2054 | jwashburn@ayvazpizza.com
      039274 | Pasadena, TX | RGM: Martha Seledon
      039284 | Seabrook, TX | RGM: Lauren Bock-Yeager
      039285 | La Porte, TX | RGM: Richardo Castro
      039297 | Pasadena, TX | RGM: Hector Mosqueda
      039309 | Pasadena, TX | RGM: Frank Elsik
      039463 | League City, TX | RGM: Kristin King
      039515 | Webster, TX | RGM: Jennifer Crozier

    AC: Maria Delgado-Perez | Area 2006 | mperez@ayvazpizza.com
      039255 | Houston, TX | RGM: German Ajucum
      039271 | Houston, TX | RGM: Sandra O'Malley
      039288 | Houston, TX | RGM: James Keaton
      039311 | Houston, TX | RGM: Adrian Marquez
      039322 | Houston, TX | RGM: Ana Nunez
      039444 | Houston, TX | RGM: Camerino Correa
      042806 | Pearland, TX | RGM: Jaime Guerrero

    AC: Rachel Hightower | Area 2045 | rhightower@ayvazpizza.com
      039269 | Houston, TX | RGM: Herman Davis
      039279 | Pearland, TX | RGM: Cynthia Nellums
      039280 | Friendswood, TX | RGM: Mehar Unnisa Khanam
      039286 | Pearland, TX | RGM: James Selby
      039290 | Pearland, TX | RGM: Kathryn High
      039312 | League City, TX | RGM: Veronica Jones
      039313 | Houston, TX | RGM: India Scott
      039330 | Manvel, TX | RGM: Teresa Hanley

    AC: Ravin Lott | Area 2051 | rlott@ayvazpizza.com
      039247 | Houston, TX | RGM: Thuan Ta
      039252 | Houston, TX | RGM: Paul Ward
      039260 | Houston, TX | RGM: Sergio Ruano-Reyes
      039262 | Houston, TX | RGM: Oscar Avilez
      039277 | Houston, TX | RGM: Mike Perkins
      039287 | Houston, TX | RGM: Dina Cortez
      039296 | Houston, TX | RGM: Rashad Matthews
      039307 | Houston, TX | RGM: Everett Dennis

    AC: Reginald Brown | Area 2046 | rbrown@ayvazpizza.com
      039256 | Houston, TX | RGM: Tayler Christian
      039257 | Missouri City, TX | RGM: Michael McMillan
      039263 | Houston, TX | RGM: Fatima Brailey
      039265 | Houston, TX | RGM: Darrell Thomas
      039270 | Missouri City, TX | RGM: Michael Tubbs Jr
      039292 | Fresno, TX | RGM: Nkem Wilson
      040395 | Rosharon, TX | RGM: Patricia Richards

    AC: Robert Thomas | Area 2037 | rthomas@ayvazpizza.com
      039276 | Texas City, TX | RGM: Katherine Leonard-Cook
      039282 | Alvin, TX | RGM: Jose Useda
      039301 | La Marque, TX | RGM: Rhiannon Hernandez
      039306 | Lake Jackson, TX | RGM: Teresa Harper
      039310 | Angleton, TX | RGM: Robert Potter
      039314 | Dickinson, TX | RGM: Avis Hawkins
      039328 | Santa Fe, TX | RGM: Audrianna Lawver
      039334 | Galveston, TX | RGM: Mitchell Lewis

    AC: Shayda Willison | Area 2059 | swillison@ayvazpizza.com
      039258 | Sugar Land, TX | RGM: Patricio Matias Santos
      039259 | Sugar Land, TX | RGM: Austin Wagner
      039264 | Houston, TX | RGM: Charles Ouedraogo
      039273 | Houston, TX | RGM: Reshad Lewis
      039278 | Meadows Place, TX | RGM: Derek Putch
      039283 | Houston, TX | RGM: Eric Figueroa
      039302 | Sugar Land, TX | RGM: Brittany Schottle
      041467 | Richmond, TX | RGM: Jayme Mcfadden

  Region Coach: Terrance Spillane

    AC: Brenda Marta | Area 2002 | bmarta@ayvazpizza.com
      040090 | Las Cruces, NM | RGM: Victor Banuelos
      040091 | Silver City, NM | RGM: OPEN
      040093 | Las Cruces, NM | RGM: Yasmine Santos
      040102 | Deming, NM | RGM: Roy Smith

    AC: Constance Miranda | Area 2010 | cmiranda@ayvazpizza.com
      039182 | El Paso, TX | RGM: Roger Flores
      039185 | El Paso, TX | RGM: Roberto Vega
      039318 | Socorro, TX | RGM: Roy Murillo Sr
      039323 | El Paso, TX | RGM: Ginger Patti
      041651 | El Paso, TX | RGM: Crystal Gallegos

    AC: Eric Harstine | Area 2033 | eharstine@ayvazpizza.com
      040082 | Albuquerque, NM | RGM: Brian Showalter
      040084 | Albuquerque, NM | RGM: Jasen Cordova
      040095 | Grants, NM | RGM: David Goodpasture
      040101 | Albuquerque, NM | RGM: Adrian Martinez
      040107 | Albuquerque, NM | RGM: Michael Serna
      040108 | Albuquerque, NM | RGM: Nicole Wells
      040111 | Albuquerque, NM | RGM: Michael Havens

    AC: Javier Martinez | Area 2024 | jmartinez@ayvazpizza.com
      038729 | El Paso, TX | RGM: Skylar Meadows
      039174 | El Paso, TX | RGM: Jose Chuca
      039175 | El Paso, TX | RGM: Aaron Granados
      039178 | El Paso, TX | RGM: Abelardo Gonzalez
      039192 | El Paso, TX | RGM: Jose Villegas
      039324 | El Paso, TX | RGM: Carlos Rangel
      039448 | El Paso, TX | RGM: Guadalupe Nino

    AC: Kevin Dunn | Area 2055 | kdunn@ayvazpizza.com
      040088 | Los Lunas, NM | RGM: Kyla Simmons
      040096 | Belen, NM | RGM: Alexandra Duran-Sanchez
      040099 | Albuquerque, NM | RGM: Cruzito Garcia
      040100 | Truth Or Consequences, NM | RGM: OPEN
      040110 | Albuquerque, NM | RGM: Ricardo Marquez

    AC: Max Losey | Area 2039 | mlosey@ayvazpizza.com
      039589 | Rio Rancho, NM | RGM: Alan Eberhard
      040094 | Santa Fe, NM | RGM: John Rivera
      040104 | Rio Rancho, NM | RGM: Enoc Hackleen
      040105 | Las Vegas, NM | RGM: Phillip Segura
      040106 | Espanola, NM | RGM: Ashley Martinez
      040109 | Albuquerque, NM | RGM: Angela Pineda Contreras

    AC: Oscar Gutierrez | Area 2043 | ogutierrez@ayvazpizza.com
      039173 | El Paso, TX | RGM: Stephanie Florence
      039176 | Lovington, NM | RGM: Gloria Carrillo
      039177 | Hobbs, NM | RGM: America Juarez
      039179 | El Paso, TX | RGM: Cedric Smith
      039188 | Carlsbad, NM | RGM: Sylvia Rodriguez
      039518 | Hobbs, NM | RGM: Crystal Putman
      039530 | El Paso, TX | RGM: Delilah Gomez

    AC: Tami Elliott-Baker | Area 2008 | tbaker@ayvazpizza.com
      040083 | Farmington, NM | RGM: Brian Gravgaard
      040085 | Gallup, NM | RGM: Marco Sanchez
      040086 | Farmington, NM | RGM: Cynthia Harrison
      040087 | Gallup, NM | RGM: Natasha Romero
      040092 | Aztec, NM | RGM: OPEN
      040112 | Durango, CO | RGM: Scott Latschar

  Region Coach: Theresa McDaniel

    AC: Bahram Kaman | Area 2025 | bkaman@ayvazpizza.com
      039224 | Kenedy, TX | RGM: Sarah Baker
      039235 | San Antonio, TX | RGM: Anna Lopez
      039237 | Floresville, TX | RGM: Kassandra Mendoza (Bumgardner)
      039316 | LaVernia, TX | RGM: Priscilla Gamboa
      041058 | Schertz, TX | RGM: April DeLauter

    AC: Brian Marzan | Area 2032 | bmarzan@ayvazpizza.com
      039158 | Mathis, TX | RGM: Jessica Pina
      039159 | Sinton, TX | RGM: Patricia Beckmann
      039184 | Portland, TX | RGM: Harvey Murbarger
      039189 | Rockport, TX | RGM: Edwardo Gonzales Garcia
      039332 | Ingleside, TX | RGM: Carmen Gonzales
      039374 | Beeville, TX | RGM: Simeon Garza

    AC: Cesar Robles | Area 2007 | crobles@ayvazpizza.com
      039167 | Kingsville, TX | RGM: Megan Smith
      039170 | Corpus Christi, TX | RGM: Macy Reed
      039171 | Robstown, TX | RGM: Merida Gonzales
      039186 | Corpus Christi, TX | RGM: Dominic Hatcher
      039191 | Alice, TX | RGM: Lawrence Bergstrom
      039194 | Corpus Christi, TX | RGM: Josephina Rodriguez
      039222 | Falfurrias, TX | RGM: Debra Rosas
      039447 | Corpus Christi, TX | RGM: James McMahan

    AC: Donna Dittmar | Area 2014 | ddittmar@ayvazpizza.com
      039163 | Castroville, TX | RGM: Gary Michlowitz
      039223 | Hondo, TX | RGM: Jimmy Ortiz
      039233 | San Antonio, TX | RGM: Jason Schwartz
      039234 | San Antonio, TX | RGM: Michael Esparza
      039243 | Pleasanton, TX | RGM: Sonya Worlds
      039315 | Devine, TX | RGM: Anita Gonzales
      039333 | San Antonio, TX | RGM: Chara Vanzant
      039514 | San Antonio, TX | RGM: Harrison Haynes

    AC: Freddy (Antonio) Sandoval | Area 2031 | fsandoval@ayvazpizza.com
      039155 | Cuero, TX | RGM: Rosa Williams
      039156 | Gonzales, TX | RGM: Cristian Grifaldo
      039157 | Yoakum, TX | RGM: Bonita Silvas
      039160 | Edna, TX | RGM: Donna Gonzales
      039161 | Port Lavaca, TX | RGM: Cassandra Briskey
      039162 | Victoria, TX | RGM: Jonathan Longoria
      039165 | Zac Lentz, TX | RGM: Isaac Velasquez
      039445 | Refugio, TX | RGM: Tina Mendoza

    AC: Jesse Luna | Area 2028 | jluna@ayvazpizza.com
      039166 | Corpus Christi, TX | RGM: Sara Hale
      039172 | Corpus Christi, TX | RGM: Ashley West
      039181 | Corpus Christi, TX | RGM: VIrginia Blaker
      039183 | Corpus Christi, TX | RGM: Robby Botello
      039187 | Corpus Christi, TX | RGM: Val Jones
      039193 | Aransas Pass, TX | RGM: Peter Garcia
      041042 | Corpus Christi, TX | RGM: Joseph Farias
      041956 | Corpus Christi, TX | RGM: Albert Rosas

    AC: Kyle Smith | Area 2056 | kylesmith@ayvazpizza.com
      039164 | Sonora, TX | RGM: Yadira Zambrano
      039225 | Kerrville, TX | RGM: Andrew Nations
      039238 | New Braunfels, TX | RGM: Lorinda Hildebrand
      039241 | Bulverde, TX | RGM: Madalon (Alec) King
      039242 | Boerne, TX | RGM: America Martinez

    AC: Luigi Andinolfi | Area 2036 | landinolfi@ayvazpizza.com
      039226 | Pearsall, TX | RGM: Destiny Moore
      039229 | San Antonio, TX | RGM: Kitti West
      039230 | San Antonio, TX | RGM: Jorge Casiano
      039231 | San Antonio, TX | RGM: Sesario Estrada
      039232 | San Antonio, TX | RGM: Mary Ramos
      039239 | San Antonio, TX | RGM: John Sanchez
      039240 | San Antonio, TX | RGM: Monica Delarosa
      039319 | San Antonio, TX | RGM: Adam Velasquez
`;

module.exports = { MASTER_ALIGNMENT_TEXT };
